extern const GeoLayout hmc_area_1_geo[];
extern const GeoLayout hmc_area_1[];
extern const Collision hmc_area_1_collision[];
extern const MacroObject hmc_area_1_macro_objs[];
extern Lights1 hmc_dl_area_proto_default__42860_lights;
extern Lights1 hmc_dl_f3dlite_material_lights;
extern Vtx hmc_dl_death_plane_a_0_mesh_layer_1_vtx_0[64];
extern Gfx hmc_dl_death_plane_a_0_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_start_plane_a_0_mesh_layer_1_vtx_0[4];
extern Gfx hmc_dl_start_plane_a_0_mesh_layer_1_tri_0[];
extern Gfx mat_hmc_dl_area_proto_default__42860[];
extern Gfx mat_hmc_dl_f3dlite_material[];
extern Gfx hmc_dl_death_plane_a_0_mesh_layer_1[];
extern Gfx hmc_dl_start_plane_a_0_mesh_layer_1[];
extern Gfx hmc_dl_material_revert_render_settings[];
