extern const GeoLayout bitfs_area_1_geo[];
extern const GeoLayout bitfs_area_1[];
extern const Collision bitfs_area_1_collision[];
extern const MacroObject bitfs_area_1_macro_objs[];
extern Lights1 bitfs_dl_area_proto_default__42860_lights;
extern Lights1 bitfs_dl_f3dlite_material_lights;
extern Vtx bitfs_dl_death_plane_a_0_mesh_layer_1_vtx_0[64];
extern Gfx bitfs_dl_death_plane_a_0_mesh_layer_1_tri_0[];
extern Vtx bitfs_dl_start_plane_a_0_mesh_layer_1_vtx_0[4];
extern Gfx bitfs_dl_start_plane_a_0_mesh_layer_1_tri_0[];
extern Gfx mat_bitfs_dl_area_proto_default__42860[];
extern Gfx mat_bitfs_dl_f3dlite_material[];
extern Gfx bitfs_dl_death_plane_a_0_mesh_layer_1[];
extern Gfx bitfs_dl_start_plane_a_0_mesh_layer_1[];
extern Gfx bitfs_dl_material_revert_render_settings[];
